### ISSUE TITLE
Basic Tile Physics

### ISSUE THREAD

**Issue by zachary-allen823** [Allen-ISD-Computer-Science/REPO_IceTilePhysics_2024#22]
Add fundamental sliding that can be used with player model within a space

**Comment by zachary-allen823** [comment]
I am going to test this on a separate project just to work on the physics and will hopefully be able to add it to the actual project on Thursday.

**Comment by BerkleyVoss** [comment]
Thursday - Helped Zachary debug.

**Comment by zachary-allen823** [comment]
Thursday - Needed to wait for assistance from Mr. Ben to solve issue to even get any movement to work.

**Comment by zachary-allen823** [comment]
Dropping use of IGIS to start working with Babylon

**Comment by zachary-allen823** [comment]
Needing to reassess and pivot to help Austin with other things. Movement can be done later and with the already established code for the cube.
