### ISSUE TITLE
Create 3D Cube Model

### ISSUE THREAD

**Issue by zachary-allen823** [Allen-ISD-Computer-Science/REPO_IceTilePhysics_2024#23]
Find a platform we can use for making 3D models and then try and make a cube we can use as a base in levels.

**Comment by BerkleyVoss** [comment]
Tuesday - Helped Luke somewhat.

**Comment by BerkleyVoss** [comment]
Tuesday - helped somewhat to make 3D cube model in Babylon

**Comment by Delikatessen** [comment]
Found Babylon.js, did extensive testing with the API and managed to create a cube platform, finished file with automated cube tile creation will be uploaded to the git when finished

**Comment by lukelento06** [comment]
Tuesday - Worked on setting up html file

Thursday - Finished up the rough base for webpage, stopped to allow update to Babylon

**Comment by rohan-natarajan** [comment]
https://playground.babylonjs.com/#AH85PF#53

**Comment by Delikatessen** [comment]
Cube Concept Art on wiki page
https://github.com/Allen-ISD-Computer-Science/REPO_IceTilePhysics_2024/wiki/Concept-Work

**Comment by Delikatessen** [comment]
New Concept Art on wiki page
[cs_2024/wiki/Concept-Work](https://github.com/Allen-ISD-Computer-Science/REPO_IceTilePhysics_2024/wiki/Concept-Work)
