### ISSUE TITLE
Babylon motion

### ISSUE THREAD

**Issue by zachary-allen823** [Allen-ISD-Computer-Science/REPO_IceTilePhysics_2024#28]
Experiment and figure out movement and arc camera tracking in 3D environment.

**Comment by rohan-natarajan** [comment]
Render all 6 sides of the randomized cube on IGIS. Randomize more than one cube face.

**Comment by rohan-natarajan** [comment]
Get a working UI and a title screen.

**Comment by rohan-natarajan** [comment]
Work on Babylon functionality on GitHub pages.

**Comment by rohan-natarajan** [comment]
https://playground.babylonjs.com/#CAUKYQ

**Comment by zachary-allen823** [comment]
I have gotten rendering down and even messed with the testing file for babylon in our repository now I just have to do motion.

**Comment by zachary-allen823** [comment]
Keyboard presses work. Need to find a way to create constant movement and then establish mechanic for boundary collision.

**Comment by zachary-allen823** [comment]
Constant movement works

**Comment by zachary-allen823** [comment]
Newest update: I have it to where I can get the object to stop when it reaches a certain point, but it's hard coded. I need a way to have it stop on collision instead of stopping on a given point.
